config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'groups#index', as: :authenticated_root
  end

  resources :groups do
    resources :expenses, except: :show
  end
  resources :users, only: %i[edit update show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  # Defines the root path route ("/")
  root 'users#splash'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(current_user)
    return unless current_user.present? # additional permissions for logged in users (they can read their own posts)

    can :manage, Group, user: current_user
    can :manage, Expense, user: current_user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :groups

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, inverse_of: 'user', foreign_key: 'user_id', dependent: :destroy
  has_many :expenses, inverse_of: 'user', foreign_key: 'user_id', dependent: :destroy

  validates :name, presence: true, length: { maximum: 25 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_user
  before_action :set_group
  before_action :set_expense, only: %i[show edit update destroy]

  # GET /expenses or /expenses.json
  def index
    @expenses = @group.expenses
  end

  # GET /expenses/new
  def new
    @expense = @user.expenses.new
    @expense.group_ids = @group.id
  end

  # GET /expenses/1/edit
  def edit; end

  # POST /expenses or /expenses.json
  def create
    @expense = @user.expenses.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to group_path(@expense.group_ids), notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to group_url(@group), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to group_path, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = current_user
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_user
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = @user.groups
  end

  # GET /groups/1 or /groups/1.json
  def show
    @expenses = @group.expenses.order(created_at: :desc)
  end

  # GET /groups/new
  def new
    @group = @user.groups.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = @user.groups.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = current_user
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  def splash; end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>" class="card flex exp">
  <p class="exp-name">
    <strong><%= expense.name %></strong>
  </p>
  <p class="exp-amount">
    $
    <strong><%= expense.amount %></strong>
  </p>
  <div class="exp-div">
    <%= link_to "✎", edit_group_expense_path(@group, expense) %>
    <% expense.groups.each do |group| %>
      <p class="exp-icon"><%= group.icon %></p>
    <% end %>
  </div>
</div>

app/views/expenses/_form.html.erb
<%= form_with(model: [@group, @expense]) do |form| %>
  <% if @expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>
      <ul>
        <% @expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>
  <div>
    <%= form.label :group_id, style: "display: block" %>
    <%= form.collection_check_boxes(:group_ids, @user.groups.order( 'name ASC' ), :id, :name) %>
  </div>
  <div>
    <%= form.submit class: "btn-main"%>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>
<% if can? :manage, @expense %>
  <%= render "form", group: @expense %>
<% else %>
  <h2>Not your GROUP. Go Back.</h2>
<% end %>
<%= link_to "Back to Group", group_path(@group), class: "btn-white" %>

app/views/expenses/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Expenses</h1>
<div id="expenses">
  <% @expenses.each do |expense| %>
    <%= render expense %>
    <p>
      <%= link_to "Show this expense", group_expense_path(@group, expense) %>
    </p>
  <% end %>
</div>
<%= link_to "New expense", new_group_expense_path(@group) %>

app/views/expenses/new.html.erb
<% provide(:title, "NEW EXPENSE") %>
<% if can? :manage, @expense %>
  <%= render "form", expense: @expense %>
<% else %>
  <h2>Not your GROUP. Go Back.</h2>
<% end %>
<%= link_to "Back to GROUP", group_path(@group), class: "btn-white" %>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>
      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :icon %>
    <%= form.select :icon, [['🎲'], ['🚘'], ['🛒'], ['🍕'], ['📚'], ['🎞️'], ['🎶'], ['🍎'],
     ['👾'], ['✍🏽'], ['🏃🏽'], ['❤️'], ['⭐'], ['🐶'], ['🌳'], ['🌎'], ['🌙'], ['💧'], ['☀️'], ['🌹'],
     ['🏈'], ['🥊'], ['✈️'], ['🏕️'], ['🚲'], ['🔨'], ['📆'], ['📎'], ['🔒'], ['📌'], ['✂️'], ['🕙'],
     ['🧳'], ['❤️'], ['⚽️'], ['🎾'], ['🤿'], ['🎨'], ['🎳'], ['🎮'], ['⛽️'], ['🏟'], ['📺'], ['🛎'],] %>
  </div>
  <div>
    <%= form.submit class: "btn-main" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<%= link_to group do %>
  <div id="<%= dom_id group %>" class="card flex">
    <p class="cat-icon">
      <strong><%= group.icon %></strong>
    </p>
    <p class="cat-name">
      <strong><%= group.name %></strong>
    </p>
    <p class="cat-total">Total:
      <strong>$ <%= group.expenses.sum(:amount) %></strong>
    </p>
  </div>
<% end %>

app/views/groups/edit.html.erb
<% provide(:title, "EDIT GROUP") %>
<% if can? :manage, @group %>
  <%= render "form", group: @group %>
<% else %>
  <h2>Not your group. Go Back.</h2>
<% end %>
<%= link_to "Back to groups", groups_path, class: "btn-white" %>

app/views/groups/index.html.erb
<% provide(:title, "GROUPS") %>
<h2 class='title'>
  <%= @user.name %>
  <%= link_to "✐", edit_user_registration_path %>
</h2>
<div id="categories" class="inner-container flex" >
  <% @groups.each do |group| %>
    <%= render group %>
  <% end %>
</div>
<%= link_to "New group", new_group_path, class: "btn-main" %>

app/views/groups/new.html.erb
<% provide(:title, "NEW GROUP") %>
<% if can? :manage, @group %>
  <%= render "form", group: @group %>
<% else %>
  <h2>Not your group. Go Back.</h2>
<% end %>
<%= link_to "Back to groups", groups_path, class: "btn-white" %>

app/views/groups/show.html.erb
<% provide(:title, "GROUP") %>
<% if can? :manage, @group %>
  <div id="categories" class="inner-container flex" >
    <%= render @group %>
  </div>
  <div id="expenses" class="inner-container flex">
    <%= render @expenses %>
  </div>
  <%= link_to "New expense", new_group_expense_path(@group, @expense), class: "btn-main" %>
  <%= link_to "Edit this group", edit_group_path(@group), class: "btn-white" %>
<% else %>
  <h2>Not your group. Go Back.</h2>
<% end %>

app/views/layouts/_navbar.html.erb
<nav id="navbar">
  <div id="nav-container">
    <div id="navbar-body">
      <ul class="navbar-list">
        <% if user_signed_in? %>
          <li class="nav-item nav-back">
            <%= link_to '◀︎', root_path %>
          </li>
        <% end %>
          <li class="nav-item nav-title">
            <%= yield(:title) %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item nav-logout">
              <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: false } %>
            </li>
          <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Spend Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Figtree:wght@300;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>
  <body>
    <main>
      <%= render partial: 'layouts/navbar' %>
      <div class="container flex">
        <h3 class="notice"><%= notice %></h3>
        <h3 class="alert"><%= alert %></h3>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>
<%= render "form", user: @user %>
<br>
<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @user %>
<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", user_path %>
  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/users/splash.html.erb
<% provide(:title, "WELCOME") %>
<div class='splash-container'>
  <%= image_tag('logo.png', class: 'splash-logo') %>
  <div class='btn-group flex'>
    <%= link_to 'Log In', new_user_session_path, class: 'btn-main' %>
    <%= link_to 'Sign Up', new_user_registration_path, class: 'btn-white' %>
  </div>
</div>